apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-health-check-operator-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-health-check-operator-rs
  template:
    metadata:
      labels:
        app: node-health-check-operator-rs
    spec:
      serviceAccountName: node-health-check-operator-rs-account
      containers:
      - name: node-health-check-operator-rs
        image: ghcr.io/nathanle/l7-health-check-operator:latest
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "20Mi"
            cpu: "100m"
        env:
          - name: KUBERNETES_SERVICE_HOST
            value: kubernetes.default.svc.cluster.local

